# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IndicadoresGeosaude
                                 A QGIS plugin
 Este plugin permite descarregar indicadores do geosaúde, adicionando-os como camadas no QGIS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-06-19
        copyright            : (C) 2018 by Márcia Esteves e Sara Oliveira
        email                : ...
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IndicadoresGeosaude class from file IndicadoresGeosaude.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .indicadores_geosaude import IndicadoresGeosaude
    return IndicadoresGeosaude(iface)
